// NOTE FOR MAINTAINERS: Strong industry-standard template modeled on the public
// privacy policies of major dating apps. NOT a substitute for review by a
// licensed privacy attorney. Confirm with counsel: your legal entity, the exact
// data you collect/share, your CCPA/CPRA & GDPR obligations, and whether you need
// a registered EU/UK representative. Placeholders marked "[[CONFIRM: ...]]".

export const metadata = {
  title: 'Privacy Policy · Wingman',
  description: 'How Wingman collects, uses, shares, and protects your information, and your rights.',
};

const UPDATED = 'July 7, 2026';

function Section({ title, children }) {
  return (
    <section>
      <h2 className="text-lg font-bold text-slate-900 mb-2">{title}</h2>
      <div className="space-y-2">{children}</div>
    </section>
  );
}

export default function PrivacyPolicyPage() {
  return (
    <main className="min-h-screen bg-background">
      <div className="max-w-2xl mx-auto px-6 py-14">
        <a href="/" className="text-sm text-[#e0447f] font-semibold">← Wingman</a>
        <h1 className="mt-4 text-3xl font-display font-extrabold text-slate-900">Privacy Policy</h1>
        <p className="mt-1 text-sm text-slate-400">Last updated {UPDATED}</p>

        <div className="mt-8 space-y-7 text-[15px] leading-relaxed text-slate-700">
          <p>
            Wingman (&ldquo;Wingman,&rdquo; &ldquo;we,&rdquo; &ldquo;us&rdquo;)
            {' '}[[CONFIRM: legal entity]] is a social matchmaking service where friends help each
            other meet people. This Privacy Policy explains what information we collect, how we use
            and share it, the choices and rights you have, and how we protect it. By using Wingman you
            agree to this Policy. If you do not agree, do not use the Service.
          </p>

          <Section title="Information we collect">
            <p>We collect information you give us, information generated by your use of the Service, and limited technical information:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li><strong>Account data</strong>: email address and password (stored only as a secure hash).</li>
              <li><strong>Profile data</strong>: name, age, school, major, year, gender, who you&rsquo;re looking for, photos, and prompt answers.</li>
              <li><strong>Sensitive data you choose to share</strong>: because this is a dating service, information you add to your profile or messages may reveal characteristics such as sexual orientation. You provide this voluntarily and consent to our processing it to operate the Service.</li>
              <li><strong>Activity data</strong>: likes, matches, the friends who swipe for you (your wingmen), notes your wingmen add, and messages you send to matches.</li>
              <li><strong>Safety data</strong>: reports, blocks, and related signals used to keep the community safe.</li>
              <li><strong>Technical data</strong>: IP address and basic device/log information used for security, rate-limiting, and abuse prevention.</li>
            </ul>
          </Section>

          <Section title="How we use your information">
            <p>We use your information to:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>create and operate your profile and account;</li>
              <li>show you and your wingmen potential matches and enable messaging with mutual matches;</li>
              <li>keep the Service secure and investigate fraud, abuse, and violations of our Terms;</li>
              <li>respond to reports and provide support;</li>
              <li>comply with legal obligations and enforce our agreements.</li>
            </ul>
            <p>We do <strong>not</strong> sell your personal information for money.</p>
          </Section>

          <Section title="Legal bases (EEA/UK users)">
            <p>
              Where the GDPR or UK GDPR applies, we process your information based on: performance of
              our contract with you (to provide the Service); your consent (for sensitive data and
              optional features); our legitimate interests (to secure and improve the Service and
              prevent abuse), balanced against your rights; and compliance with legal obligations. You
              may withdraw consent at any time, without affecting prior processing.
            </p>
          </Section>

          <Section title="How your information is shared">
            <ul className="list-disc pl-5 space-y-1">
              <li><strong>With other users</strong>: your profile is visible to other users and to the wingmen you authorize. Notes your wingmen write may be shown to the other side&rsquo;s wingmen as part of a potential match. Messages are visible to you and your match.</li>
              <li><strong>With service providers</strong>: vendors who host our infrastructure, deliver email, and provide similar operational functions, under contracts that limit their use of your data.</li>
              <li><strong>For legal reasons</strong>: to comply with law, respond to lawful requests, enforce our Terms, or protect the rights, safety, and property of Wingman, our users, or the public.</li>
              <li><strong>Business transfers</strong>: in connection with a merger, acquisition, financing, or sale of assets, your information may be transferred as a business asset, subject to this Policy.</li>
            </ul>
          </Section>

          <Section title="Your choices and rights">
            <ul className="list-disc pl-5 space-y-1">
              <li>Edit your profile and photos at any time in the app.</li>
              <li>Block or report other users from any conversation.</li>
              <li><strong>Delete your account</strong> permanently from the Profile screen. Deletion removes your profile, photos, matches, and messages, subject to the limited retention described below.</li>
            </ul>
            <p>
              Depending on where you live, you may have rights to access, correct, delete, port, or
              restrict processing of your personal information, to object to certain processing, and
              to opt out of &ldquo;sale&rdquo; or &ldquo;sharing&rdquo; of personal information as
              those terms are defined by California and other U.S. state laws. We do not sell or share
              personal information for cross-context behavioral advertising. To exercise any right,
              email{' '}
              <a href="mailto:support@wingman33.com" className="text-[#e0447f] font-semibold">support@wingman33.com</a>.
              We will not discriminate against you for exercising your rights, and we will verify your
              request before acting on it.
            </p>
          </Section>

          <Section title="Data retention">
            <p>
              We keep your information while your account is active and delete it when you delete your
              account, except where we must retain limited records to comply with legal obligations,
              resolve disputes, enforce our agreements, or address safety and fraud (for example,
              retaining a record that an account was banned for abuse). Retained data is limited to
              what is reasonably necessary for those purposes.
            </p>
          </Section>

          <Section title="Security">
            <p>
              We use reasonable technical and organizational measures to protect your information,
              including transport encryption and secure on-device storage of session tokens (iOS
              Keychain). However, <strong>no method of transmission or storage is 100% secure</strong>,
              and we cannot guarantee absolute security. You are responsible for keeping your account
              credentials confidential.
            </p>
          </Section>

          <Section title="International transfers">
            <p>
              We operate in the United States, and your information may be processed in the U.S. or
              other countries whose data-protection laws may differ from those in your country. Where
              required, we rely on appropriate safeguards (such as standard contractual clauses) for
              cross-border transfers.
            </p>
          </Section>

          <Section title="Age requirement / children">
            <p>
              Wingman is intended only for users 18 and older. We do not knowingly collect personal
              information from anyone under 18. If we learn that we have collected information from a
              person under 18, we will delete it. If you believe a minor is using the Service, contact
              us immediately.
            </p>
          </Section>

          <Section title="Cookies and analytics">
            <p>
              Our website may use cookies and similar technologies that are necessary to operate the
              Service and to understand usage in aggregate. You can control cookies through your
              browser settings. We honor applicable opt-out preference signals where required by law.
            </p>
          </Section>

          <Section title="Changes to this Policy">
            <p>
              We may update this Policy from time to time. If we make material changes, we will take
              reasonable steps to notify you and will update the &ldquo;Last updated&rdquo; date. Your
              continued use of the Service after changes take effect means you accept the updated
              Policy.
            </p>
          </Section>

          <Section title="Contact">
            <p>
              Questions about this Policy or your data, or to exercise your rights? Email{' '}
              <a href="mailto:support@wingman33.com" className="text-[#e0447f] font-semibold">support@wingman33.com</a>.
            </p>
          </Section>
        </div>
      </div>
    </main>
  );
}
