// US Colleges (alphabetical)
export const US_COLLEGES = [
  'Arizona State University',
  'Auburn University',
  'Baylor University',
  'Boston College',
  'Boston University',
  'Brigham Young University',
  'Brown University',
  'California Institute of Technology',
  'Carnegie Mellon University',
  'Clemson University',
  'Columbia University',
  'Cornell University',
  'Dartmouth College',
  'Duke University',
  'Emory University',
  'Florida State University',
  'Georgetown University',
  'Georgia Institute of Technology',
  'Harvard University',
  'Indiana University',
  'Johns Hopkins University',
  'Massachusetts Institute of Technology',
  'Michigan State University',
  'New York University',
  'North Carolina State University',
  'Northeastern University',
  'Northwestern University',
  'Ohio State University',
  'Penn State University',
  'Princeton University',
  'Purdue University',
  'Rice University',
  'Rutgers University',
  'Stanford University',
  'Syracuse University',
  'Texas A&M University',
  'Tufts University',
  'Tulane University',
  'University of Alabama',
  'University of Arizona',
  'University of California, Berkeley',
  'University of California, Los Angeles',
  'University of California, San Diego',
  'University of Chicago',
  'University of Colorado Boulder',
  'University of Connecticut',
  'University of Florida',
  'University of Georgia',
  'University of Illinois Urbana-Champaign',
  'University of Iowa',
  'University of Maryland',
  'University of Miami',
  'University of Michigan',
  'University of Minnesota',
  'University of North Carolina at Chapel Hill',
  'University of Notre Dame',
  'University of Oregon',
  'University of Pennsylvania',
  'University of Pittsburgh',
  'University of Rochester',
  'University of South Carolina',
  'University of Southern California',
  'University of Tennessee',
  'University of Texas at Austin',
  'University of Virginia',
  'University of Washington',
  'University of Wisconsin-Madison',
  'Vanderbilt University',
  'Villanova University',
  'Virginia Tech',
  'Wake Forest University',
  'Washington University in St. Louis',
  'Yale University',
];

// Common Majors (alphabetical)
export const COMMON_MAJORS = [
  'Accounting',
  'Aerospace Engineering',
  'Anthropology',
  'Architecture',
  'Art History',
  'Biochemistry',
  'Biology',
  'Biomedical Engineering',
  'Business Administration',
  'Chemical Engineering',
  'Chemistry',
  'Civil Engineering',
  'Communications',
  'Computer Engineering',
  'Computer Science',
  'Criminal Justice',
  'Data Science',
  'Economics',
  'Education',
  'Electrical Engineering',
  'English',
  'Environmental Science',
  'Film Studies',
  'Finance',
  'Graphic Design',
  'Health Sciences',
  'History',
  'Human Resources',
  'Information Systems',
  'Information Technology',
  'International Relations',
  'Journalism',
  'Kinesiology',
  'Linguistics',
  'Management',
  'Marketing',
  'Mathematics',
  'Mechanical Engineering',
  'Music',
  'Neuroscience',
  'Nursing',
  'Nutrition',
  'Philosophy',
  'Physics',
  'Political Science',
  'Pre-Law',
  'Pre-Med',
  'Psychology',
  'Public Health',
  'Public Relations',
  'Social Work',
  'Sociology',
  'Software Engineering',
  'Spanish',
  'Statistics',
  'Supply Chain Management',
  'Theater',
];

// Class Years
export const CLASS_YEARS = ['Freshman', 'Sophomore', 'Junior', 'Senior', 'Graduate', 'Other'];

// Ages (17-30)
export const AGES = Array.from({ length: 14 }, (_, i) => String(i + 17));

// Genders
export const GENDERS = ['Man', 'Woman', 'Non-binary', 'Prefer not to say', 'Other'];

// Looking For
export const LOOKING_FOR = ['Men', 'Women', 'Everyone', 'Non-binary people'];

export const SEXUALITY_OPTIONS = [
  'Straight',
  'Gay',
  'Lesbian',
  'Bisexual',
  'Pansexual',
  'Asexual',
  'Queer',
  'Prefer not to say',
  'Other',
];

// Personality Options
export const PERSONALITY_OPTIONS = [
  'Introvert',
  'Extrovert',
  'Ambivert',
];

// Cuisine Options
export const CUISINE_OPTIONS = [
  'American',
  'Chinese',
  'French',
  'Greek',
  'Indian',
  'Italian',
  'Japanese',
  'Korean',
  'Mediterranean',
  'Mexican',
  'Middle Eastern',
  'Thai',
  'Vietnamese',
  'Other',
];

export const RACE_ETHNICITY_OPTIONS = [
  'American Indian or Alaska Native',
  'Asian',
  'Black or African American',
  'East Asian',
  'Hispanic or Latino',
  'Middle Eastern or North African',
  'Native Hawaiian or Pacific Islander',
  'South Asian',
  'Southeast Asian',
  'White',
  'Multiracial',
  'Prefer not to say',
  'Self-describe',
];

export const SUBSTANCE_USE_OPTIONS = [
  'Never',
  'Rarely',
  'Socially',
  'Sometimes',
  'Often',
  'Prefer not to say',
];

// Profile Prompts
export const PROFILE_PROMPTS = [
  'What if I told you that',
  'Dating me is like',
  'Together, we could',
  "I'm looking for",
  'The way to win me over is',
  'My biggest fear is',
  "I'm convinced that",
  'This year I really want to',
  "My go-to stress reliever...",
  "The way to my heart is...",
  "We'll get along if...",
  "My most controversial opinion...",
  "I'm secretly really good at...",
  "A perfect weekend for me...",
  "My hidden talent is...",
  "I geek out about...",
];
