export const CLASS_YEARS = ['Freshman', 'Sophomore', 'Junior', 'Senior', 'Graduate', 'Alumni'];

export const GENDERS = ['Man', 'Woman', 'Non-binary', 'Other'];

export const LOOKING_FOR = ['Men', 'Women', 'Everyone', 'Non-binary people'];

export const US_COLLEGES = [
  'Arizona State University',
  'Auburn University',
  'Baylor University',
  'Boston College',
  'Boston University',
  'Brigham Young University',
  'Brown University',
  'California Institute of Technology',
  'Carnegie Mellon University',
  'Clemson University',
  'Columbia University',
  'Cornell University',
  'Dartmouth College',
  'Duke University',
  'Emory University',
  'Florida State University',
  'Georgetown University',
  'Georgia Institute of Technology',
  'Harvard University',
  'Indiana University Bloomington',
  'Johns Hopkins University',
  'Massachusetts Institute of Technology',
  'Michigan State University',
  'New York University',
  'Northeastern University',
  'Northwestern University',
  'Ohio State University',
  'Pennsylvania State University',
  'Princeton University',
  'Purdue University',
  'Rice University',
  'Rutgers University',
  'Stanford University',
  'Syracuse University',
  'Temple University',
  'Texas A&M University',
  'Tufts University',
  'Tulane University',
  'University of Alabama',
  'University of Arizona',
  'University of California, Berkeley',
  'University of California, Davis',
  'University of California, Irvine',
  'University of California, Los Angeles',
  'University of California, San Diego',
  'University of California, Santa Barbara',
  'University of Central Florida',
  'University of Chicago',
  'University of Colorado Boulder',
  'University of Connecticut',
  'University of Delaware',
  'University of Florida',
  'University of Georgia',
  'University of Illinois Urbana-Champaign',
  'University of Iowa',
  'University of Kansas',
  'University of Kentucky',
  'University of Maryland',
  'University of Massachusetts Amherst',
  'University of Miami',
  'University of Michigan',
  'University of Minnesota Twin Cities',
  'University of North Carolina at Chapel Hill',
  'University of Notre Dame',
  'University of Oregon',
  'University of Pennsylvania',
  'University of Pittsburgh',
  'University of South Carolina',
  'University of Southern California',
  'University of Tennessee',
  'University of Texas at Austin',
  'University of Virginia',
  'University of Washington',
  'University of Wisconsin-Madison',
  'Vanderbilt University',
  'Villanova University',
  'Virginia Tech',
  'Wake Forest University',
  'Washington University in St. Louis',
  'Yale University',
];

export const US_MAJORS = [
  'Accounting',
  'Aerospace Engineering',
  'Anthropology',
  'Architecture',
  'Art History',
  'Biochemistry',
  'Biology',
  'Biomedical Engineering',
  'Business Administration',
  'Chemical Engineering',
  'Chemistry',
  'Civil Engineering',
  'Communications',
  'Computer Engineering',
  'Computer Science',
  'Criminal Justice',
  'Data Science',
  'Economics',
  'Education',
  'Electrical Engineering',
  'English',
  'Environmental Science',
  'Finance',
  'Fine Arts',
  'Graphic Design',
  'History',
  'Information Systems',
  'International Relations',
  'Journalism',
  'Kinesiology',
  'Marketing',
  'Mathematics',
  'Mechanical Engineering',
  'Music',
  'Neuroscience',
  'Nursing',
  'Philosophy',
  'Physics',
  'Political Science',
  'Pre-Dental',
  'Pre-Law',
  'Pre-Med',
  'Psychology',
  'Public Health',
  'Social Work',
  'Sociology',
  'Statistics',
  'Theater',
  'Undecided',
];

export const PROMPT_GROUPS = [
  [
    'A perfect weekend is',
    'My green flag is',
    'The way to my heart is',
    'I will never shut up about',
    'My simple pleasure is',
    'A life goal of mine is',
  ],
  [
    'Together we could',
    'My ideal first date is',
    'Two truths and a lie',
    'The best way to ask me out is',
    'A random fact I love is',
    'I geek out on',
  ],
  [
    'My friends would describe me as',
    'Dating me is like',
    'I am looking for',
    'The key to my heart is',
    'One thing you should know about me is',
    'I want someone who',
  ],
];
